# -*- coding: utf-8 -*-
"""adversarialai_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsPR5B1u6loIK9tWWwGYNG9h3BThQTup
"""

#importing all the necessary library here
import pandas as pd

#reading CSV File or Upload
tableData = pd.read_csv('VolumeAndNVbySymbol_wRand.csv')
#print(tableData.describe)
print(tableData.dtypes)

#getting the number of rows
totalRows = len(tableData)
print(totalRows)
# it is printing 643214 which is correct

#setting pandas to display values in decimal notation
pd.set_option('display.float_format','{:.2f}'.format)

#get the numerical column only
numericColumns = tableData.select_dtypes(include=['number']).mean()
print(numericColumns)

#section to process time based column
tableData['Time'] = pd.to_datetime(tableData['Time'])
#print(tableData)
#printing min time
minTime = tableData.min()
print(f"Minimum Time: {minTime['Time']}")
#printing max time
maxTime = tableData.max()
print(f"Maximum Time: {maxTime['Time']}")