# -*- coding: utf-8 -*-
"""adversarialai_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KsPR5B1u6loIK9tWWwGYNG9h3BThQTup
"""

#import all the necessary library
import pandas as pd

#reading CSV File or Upload
tableData = pd.read_csv('VolumeAndNVbySymbol_wRand.csv')
#print(tableData.describe)
print(f"All the data types: {tableData.dtypes}")

#getting and printing the number of rows
totalRows = len(tableData)
print(f"Total number of rows: {totalRows}")
# it is printing 643214 which is correct

#setting pandas to display values in decimal notation
pd.set_option('display.float_format','{:.2f}'.format)

#processing numerical column
#printing The average value of each numerical column
numericColumns = tableData.select_dtypes(include=['number']).mean()
for column, value in numericColumns.items():
    print(f"Average of {column} is {value: .2f}")

#section to process time based column
tableData['Time'] = pd.to_datetime(tableData['Time'])
#print(tableData)
#printing min time
minTime = tableData.min()
print(f"Minimum Time: {minTime['Time']}")
#printing max time
maxTime = tableData.max()
print(f"Maximum Time: {maxTime['Time']}")